trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Tasks/*

pool:
  vmImage: 'windows-latest'

steps:
- task: TfxInstaller@3
  inputs:
    version: 'v0.9.x'
    
- task: PackageAzureDevOpsExtension@3
  inputs:
    rootFolder: 'Tasks'
    patternManifest: 'vss-ssrs-reports-deployment-extesnsion.json'
    outputPath: 'ssrs-reports-deployment.vsix'
    updateTasksVersion: false

- task: PublishAzureDevOpsExtension@3
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'Marketplace'
    fileType: 'vsix'
    vsixFile: 'ssrs-reports-deployment.vsix'
